// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofencodercurrentcompressedbitrate_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int copyofencodercurrentcompressedbitrate = 10;
	/// <summary>PID: 11 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofencoderautochromaweight_11 = 11;
	/// <summary>PID: 11 | Type: read</summary>
	public const int copyofencoderautochromaweight = 11;
	/// <summary>PID: 12 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofencoderchromaweight_12 = 12;
	/// <summary>PID: 12 | Type: read</summary>
	public const int copyofencoderchromaweight = 12;
	/// <summary>PID: 13 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofencoderlosslessmode_13 = 13;
	/// <summary>PID: 13 | Type: read</summary>
	public const int copyofencoderlosslessmode = 13;
	/// <summary>PID: 14 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofdecodercurrentcompressedbitrate_14 = 14;
	/// <summary>PID: 14 | Type: read</summary>
	public const int copyofdecodercurrentcompressedbitrate = 14;
	/// <summary>PID: 15 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofdecoderprogressionorder_15 = 15;
	/// <summary>PID: 15 | Type: read</summary>
	public const int copyofdecoderprogressionorder = 15;
	/// <summary>PID: 16 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofdecodercodeblockwidth_16 = 16;
	/// <summary>PID: 16 | Type: read</summary>
	public const int copyofdecodercodeblockwidth = 16;
	/// <summary>PID: 17 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int copyofdecodercodeblockheight_17 = 17;
	/// <summary>PID: 17 | Type: read</summary>
	public const int copyofdecodercodeblockheight = 17;
	/// <summary>PID: 100 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderstatus_100 = 100;
	/// <summary>PID: 100 | Type: read</summary>
	public const int encoderstatus = 100;
	/// <summary>PID: 102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodercurrentcompressedbitrate_102 = 102;
	/// <summary>PID: 102 | Type: read</summary>
	public const int encodercurrentcompressedbitrate = 102;
	/// <summary>PID: 103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderautochromaweight_103 = 103;
	/// <summary>PID: 103 | Type: read</summary>
	public const int encoderautochromaweight = 103;
	/// <summary>PID: 105 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderchromaweight_105 = 105;
	/// <summary>PID: 105 | Type: read</summary>
	public const int encoderchromaweight = 105;
	/// <summary>PID: 107 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderlosslessmode_107 = 107;
	/// <summary>PID: 107 | Type: read</summary>
	public const int encoderlosslessmode = 107;
	/// <summary>PID: 200 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderstatus_200 = 200;
	/// <summary>PID: 200 | Type: read</summary>
	public const int decoderstatus = 200;
	/// <summary>PID: 202 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercurrentcompressedbitrate_202 = 202;
	/// <summary>PID: 202 | Type: read</summary>
	public const int decodercurrentcompressedbitrate = 202;
	/// <summary>PID: 203 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderprogressionorder_203 = 203;
	/// <summary>PID: 203 | Type: read</summary>
	public const int decoderprogressionorder = 203;
	/// <summary>PID: 205 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercodeblockwidth_205 = 205;
	/// <summary>PID: 205 | Type: read</summary>
	public const int decodercodeblockwidth = 205;
	/// <summary>PID: 206 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercodeblockheight_206 = 206;
	/// <summary>PID: 206 | Type: read</summary>
	public const int decodercodeblockheight = 206;
	public class Write
	{
		/// <summary>PID: 101 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderstatus_101 = 101;
		/// <summary>PID: 101 | Type: write</summary>
		public const int encoderstatus = 101;
		/// <summary>PID: 104 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderautochromaweight_104 = 104;
		/// <summary>PID: 104 | Type: write</summary>
		public const int encoderautochromaweight = 104;
		/// <summary>PID: 106 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderchromaweight_106 = 106;
		/// <summary>PID: 106 | Type: write</summary>
		public const int encoderchromaweight = 106;
		/// <summary>PID: 108 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderlosslessmode_108 = 108;
		/// <summary>PID: 108 | Type: write</summary>
		public const int encoderlosslessmode = 108;
		/// <summary>PID: 201 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderstatus_201 = 201;
		/// <summary>PID: 201 | Type: write</summary>
		public const int decoderstatus = 201;
		/// <summary>PID: 204 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderprogressionorder_204 = 204;
		/// <summary>PID: 204 | Type: write</summary>
		public const int decoderprogressionorder = 204;
	}
}
public class WriteParameters
{
	/// <summary>PID: 101  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderstatus {get { return Protocol.GetParameter(101); }set { Protocol.SetParameter(101, value); }}
	/// <summary>PID: 104  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderautochromaweight {get { return Protocol.GetParameter(104); }set { Protocol.SetParameter(104, value); }}
	/// <summary>PID: 106  | Type: write</summary>
	public System.Object Encoderchromaweight {get { return Protocol.GetParameter(106); }set { Protocol.SetParameter(106, value); }}
	/// <summary>PID: 108  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderlosslessmode {get { return Protocol.GetParameter(108); }set { Protocol.SetParameter(108, value); }}
	/// <summary>PID: 201  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return Protocol.GetParameter(201); }set { Protocol.SetParameter(201, value); }}
	/// <summary>PID: 204  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Decoderprogressionorder {get { return Protocol.GetParameter(204); }set { Protocol.SetParameter(204, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Notavailable__fixed { get; set; }
	object Setstatustodisabled__fixed { get; set; }
	object Setstatustoenabled__fixed { get; set; }
	object Copyofencodercurrentcompressedbitrate_10 { get; set; }
	object Copyofencodercurrentcompressedbitrate { get; set; }
	object Copyofencoderautochromaweight_11 { get; set; }
	object Copyofencoderautochromaweight { get; set; }
	object Copyofencoderchromaweight_12 { get; set; }
	object Copyofencoderchromaweight { get; set; }
	object Copyofencoderlosslessmode_13 { get; set; }
	object Copyofencoderlosslessmode { get; set; }
	object Copyofdecodercurrentcompressedbitrate_14 { get; set; }
	object Copyofdecodercurrentcompressedbitrate { get; set; }
	object Copyofdecoderprogressionorder_15 { get; set; }
	object Copyofdecoderprogressionorder { get; set; }
	object Copyofdecodercodeblockwidth_16 { get; set; }
	object Copyofdecodercodeblockwidth { get; set; }
	object Copyofdecodercodeblockheight_17 { get; set; }
	object Copyofdecodercodeblockheight { get; set; }
	object Encoderstatus_100 { get; set; }
	object Encoderstatus { get; set; }
	object Encoderstatus_101 { get; set; }
	object Encodercurrentcompressedbitrate_102 { get; set; }
	object Encodercurrentcompressedbitrate { get; set; }
	object Encoderautochromaweight_103 { get; set; }
	object Encoderautochromaweight { get; set; }
	object Encoderautochromaweight_104 { get; set; }
	object Encoderchromaweight_105 { get; set; }
	object Encoderchromaweight { get; set; }
	object Encoderchromaweight_106 { get; set; }
	object Encoderlosslessmode_107 { get; set; }
	object Encoderlosslessmode { get; set; }
	object Encoderlosslessmode_108 { get; set; }
	object Decoderstatus_200 { get; set; }
	object Decoderstatus { get; set; }
	object Decoderstatus_201 { get; set; }
	object Decodercurrentcompressedbitrate_202 { get; set; }
	object Decodercurrentcompressedbitrate { get; set; }
	object Decoderprogressionorder_203 { get; set; }
	object Decoderprogressionorder { get; set; }
	object Decoderprogressionorder_204 { get; set; }
	object Decodercodeblockwidth_205 { get; set; }
	object Decodercodeblockwidth { get; set; }
	object Decodercodeblockheight_206 { get; set; }
	object Decodercodeblockheight { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 2  | Type: fixed</summary>
	public System.Object Notavailable__fixed {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 3  | Type: fixed</summary>
	public System.Object Setstatustodisabled__fixed {get { return GetParameter(3); }set { SetParameter(3, value); }}
	/// <summary>PID: 4  | Type: fixed</summary>
	public System.Object Setstatustoenabled__fixed {get { return GetParameter(4); }set { SetParameter(4, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofencodercurrentcompressedbitrate_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	public System.Object Copyofencodercurrentcompressedbitrate {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofencoderautochromaweight_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 11  | Type: read</summary>
	public System.Object Copyofencoderautochromaweight {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofencoderchromaweight_12 {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 12  | Type: read</summary>
	public System.Object Copyofencoderchromaweight {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 13  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofencoderlosslessmode_13 {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 13  | Type: read</summary>
	public System.Object Copyofencoderlosslessmode {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 14  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofdecodercurrentcompressedbitrate_14 {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 14  | Type: read</summary>
	public System.Object Copyofdecodercurrentcompressedbitrate {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 15  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofdecoderprogressionorder_15 {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 15  | Type: read</summary>
	public System.Object Copyofdecoderprogressionorder {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 16  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofdecodercodeblockwidth_16 {get { return GetParameter(16); }set { SetParameter(16, value); }}
	/// <summary>PID: 16  | Type: read</summary>
	public System.Object Copyofdecodercodeblockwidth {get { return GetParameter(16); }set { SetParameter(16, value); }}
	/// <summary>PID: 17  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Copyofdecodercodeblockheight_17 {get { return GetParameter(17); }set { SetParameter(17, value); }}
	/// <summary>PID: 17  | Type: read</summary>
	public System.Object Copyofdecodercodeblockheight {get { return GetParameter(17); }set { SetParameter(17, value); }}
	/// <summary>PID: 100  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatus_100 {get { return GetParameter(100); }set { SetParameter(100, value); }}
	/// <summary>PID: 100  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderstatus {get { return GetParameter(100); }set { SetParameter(100, value); }}
	/// <summary>PID: 101  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderstatus_101 {get { return GetParameter(101); }set { SetParameter(101, value); }}
	/// <summary>PID: 102  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodercurrentcompressedbitrate_102 {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 102  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encodercurrentcompressedbitrate {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 103  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_103 {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 103  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderautochromaweight {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 104  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_104 {get { return GetParameter(104); }set { SetParameter(104, value); }}
	/// <summary>PID: 105  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderchromaweight_105 {get { return GetParameter(105); }set { SetParameter(105, value); }}
	/// <summary>PID: 105  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderchromaweight {get { return GetParameter(105); }set { SetParameter(105, value); }}
	/// <summary>PID: 106  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderchromaweight_106 {get { return GetParameter(106); }set { SetParameter(106, value); }}
	/// <summary>PID: 107  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderlosslessmode_107 {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 107  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderlosslessmode {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 108  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderlosslessmode_108 {get { return GetParameter(108); }set { SetParameter(108, value); }}
	/// <summary>PID: 200  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_200 {get { return GetParameter(200); }set { SetParameter(200, value); }}
	/// <summary>PID: 200  | Type: read | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Decoderstatus {get { return GetParameter(200); }set { SetParameter(200, value); }}
	/// <summary>PID: 201  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderstatus_201 {get { return GetParameter(201); }set { SetParameter(201, value); }}
	/// <summary>PID: 202  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercurrentcompressedbitrate_202 {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 202  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercurrentcompressedbitrate {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 203  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderprogressionorder_203 {get { return GetParameter(203); }set { SetParameter(203, value); }}
	/// <summary>PID: 203  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decoderprogressionorder {get { return GetParameter(203); }set { SetParameter(203, value); }}
	/// <summary>PID: 204  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderprogressionorder_204 {get { return GetParameter(204); }set { SetParameter(204, value); }}
	/// <summary>PID: 205  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercodeblockwidth_205 {get { return GetParameter(205); }set { SetParameter(205, value); }}
	/// <summary>PID: 205  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercodeblockwidth {get { return GetParameter(205); }set { SetParameter(205, value); }}
	/// <summary>PID: 206  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercodeblockheight_206 {get { return GetParameter(206); }set { SetParameter(206, value); }}
	/// <summary>PID: 206  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercodeblockheight {get { return GetParameter(206); }set { SetParameter(206, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
