// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 50 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int operationmode_50 = 50;
	/// <summary>PID: 50 | Type: read</summary>
	public const int operationmode = 50;
	/// <summary>PID: 102 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodercurrentcompressedbitrate_102 = 102;
	/// <summary>PID: 102 | Type: read</summary>
	public const int encodercurrentcompressedbitrate = 102;
	/// <summary>PID: 103 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderautochromaweight_103 = 103;
	/// <summary>PID: 103 | Type: read</summary>
	public const int encoderautochromaweight = 103;
	/// <summary>PID: 105 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderchromaweight_105 = 105;
	/// <summary>PID: 105 | Type: read</summary>
	public const int encoderchromaweight = 105;
	/// <summary>PID: 107 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encoderlosslessmode_107 = 107;
	/// <summary>PID: 107 | Type: read</summary>
	public const int encoderlosslessmode = 107;
	/// <summary>PID: 109 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int encodertitle_109 = 109;
	/// <summary>PID: 109 | Type: read</summary>
	public const int encodertitle = 109;
	/// <summary>PID: 202 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercurrentcompressedbitrate_202 = 202;
	/// <summary>PID: 202 | Type: read</summary>
	public const int decodercurrentcompressedbitrate = 202;
	/// <summary>PID: 203 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decoderprogressionorder_203 = 203;
	/// <summary>PID: 203 | Type: read</summary>
	public const int decoderprogressionorder = 203;
	/// <summary>PID: 205 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercodeblockwidth_205 = 205;
	/// <summary>PID: 205 | Type: read</summary>
	public const int decodercodeblockwidth = 205;
	/// <summary>PID: 206 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodercodeblockheight_206 = 206;
	/// <summary>PID: 206 | Type: read</summary>
	public const int decodercodeblockheight = 206;
	/// <summary>PID: 207 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int decodertitle_207 = 207;
	/// <summary>PID: 207 | Type: read</summary>
	public const int decodertitle = 207;
	public class Write
	{
		/// <summary>PID: 51 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int operationmode_51 = 51;
		/// <summary>PID: 51 | Type: write</summary>
		public const int operationmode = 51;
		/// <summary>PID: 104 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderautochromaweight_104 = 104;
		/// <summary>PID: 104 | Type: write</summary>
		public const int encoderautochromaweight = 104;
		/// <summary>PID: 106 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderchromaweight_106 = 106;
		/// <summary>PID: 106 | Type: write</summary>
		public const int encoderchromaweight = 106;
		/// <summary>PID: 108 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int encoderlosslessmode_108 = 108;
		/// <summary>PID: 108 | Type: write</summary>
		public const int encoderlosslessmode = 108;
		/// <summary>PID: 204 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int decoderprogressionorder_204 = 204;
		/// <summary>PID: 204 | Type: write</summary>
		public const int decoderprogressionorder = 204;
	}
}
public class WriteParameters
{
	/// <summary>PID: 51  | Type: write | DISCREETS: Encoder = 0, Decoder = 1</summary>
	public System.Object Operationmode {get { return Protocol.GetParameter(51); }set { Protocol.SetParameter(51, value); }}
	/// <summary>PID: 104  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderautochromaweight {get { return Protocol.GetParameter(104); }set { Protocol.SetParameter(104, value); }}
	/// <summary>PID: 106  | Type: write</summary>
	public System.Object Encoderchromaweight {get { return Protocol.GetParameter(106); }set { Protocol.SetParameter(106, value); }}
	/// <summary>PID: 108  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	public System.Object Encoderlosslessmode {get { return Protocol.GetParameter(108); }set { Protocol.SetParameter(108, value); }}
	/// <summary>PID: 204  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	public System.Object Decoderprogressionorder {get { return Protocol.GetParameter(204); }set { Protocol.SetParameter(204, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Bitratetimertick_dummy { get; set; }
	object Operationmode_50 { get; set; }
	object Operationmode { get; set; }
	object Operationmode_51 { get; set; }
	object Encodercurrentcompressedbitrate_102 { get; set; }
	object Encodercurrentcompressedbitrate { get; set; }
	object Encoderautochromaweight_103 { get; set; }
	object Encoderautochromaweight { get; set; }
	object Encoderautochromaweight_104 { get; set; }
	object Encoderchromaweight_105 { get; set; }
	object Encoderchromaweight { get; set; }
	object Encoderchromaweight_106 { get; set; }
	object Encoderlosslessmode_107 { get; set; }
	object Encoderlosslessmode { get; set; }
	object Encoderlosslessmode_108 { get; set; }
	object Encodertitle_109 { get; set; }
	object Encodertitle { get; set; }
	object Decodercurrentcompressedbitrate_202 { get; set; }
	object Decodercurrentcompressedbitrate { get; set; }
	object Decoderprogressionorder_203 { get; set; }
	object Decoderprogressionorder { get; set; }
	object Decoderprogressionorder_204 { get; set; }
	object Decodercodeblockwidth_205 { get; set; }
	object Decodercodeblockwidth { get; set; }
	object Decodercodeblockheight_206 { get; set; }
	object Decodercodeblockheight { get; set; }
	object Decodertitle_207 { get; set; }
	object Decodertitle { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(1); }set { SetParameter(1, value); }}
	/// <summary>PID: 5  | Type: dummy</summary>
	public System.Object Bitratetimertick_dummy {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 50  | Type: read | DISCREETS: Encoder = 0, Decoder = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Operationmode_50 {get { return GetParameter(50); }set { SetParameter(50, value); }}
	/// <summary>PID: 50  | Type: read | DISCREETS: Encoder = 0, Decoder = 1</summary>
	public System.Object Operationmode {get { return GetParameter(50); }set { SetParameter(50, value); }}
	/// <summary>PID: 51  | Type: write | DISCREETS: Encoder = 0, Decoder = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Operationmode_51 {get { return GetParameter(51); }set { SetParameter(51, value); }}
	/// <summary>PID: 102  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodercurrentcompressedbitrate_102 {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 102  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encodercurrentcompressedbitrate {get { return GetParameter(102); }set { SetParameter(102, value); }}
	/// <summary>PID: 103  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_103 {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 103  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderautochromaweight {get { return GetParameter(103); }set { SetParameter(103, value); }}
	/// <summary>PID: 104  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderautochromaweight_104 {get { return GetParameter(104); }set { SetParameter(104, value); }}
	/// <summary>PID: 105  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderchromaweight_105 {get { return GetParameter(105); }set { SetParameter(105, value); }}
	/// <summary>PID: 105  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderchromaweight {get { return GetParameter(105); }set { SetParameter(105, value); }}
	/// <summary>PID: 106  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderchromaweight_106 {get { return GetParameter(106); }set { SetParameter(106, value); }}
	/// <summary>PID: 107  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderlosslessmode_107 {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 107  | Type: read | DISCREETS: Disabled = 0, Enabled = 1 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Encoderlosslessmode {get { return GetParameter(107); }set { SetParameter(107, value); }}
	/// <summary>PID: 108  | Type: write | DISCREETS: Disabled = 0, Enabled = 1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encoderlosslessmode_108 {get { return GetParameter(108); }set { SetParameter(108, value); }}
	/// <summary>PID: 109  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Encodertitle_109 {get { return GetParameter(109); }set { SetParameter(109, value); }}
	/// <summary>PID: 109  | Type: read</summary>
	public System.Object Encodertitle {get { return GetParameter(109); }set { SetParameter(109, value); }}
	/// <summary>PID: 202  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercurrentcompressedbitrate_202 {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 202  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercurrentcompressedbitrate {get { return GetParameter(202); }set { SetParameter(202, value); }}
	/// <summary>PID: 203  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderprogressionorder_203 {get { return GetParameter(203); }set { SetParameter(203, value); }}
	/// <summary>PID: 203  | Type: read | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4 | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decoderprogressionorder {get { return GetParameter(203); }set { SetParameter(203, value); }}
	/// <summary>PID: 204  | Type: write | DISCREETS: LCRP = 0, RLCP = 1, RPCL = 2, PCRL = 3, CPRL = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decoderprogressionorder_204 {get { return GetParameter(204); }set { SetParameter(204, value); }}
	/// <summary>PID: 205  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercodeblockwidth_205 {get { return GetParameter(205); }set { SetParameter(205, value); }}
	/// <summary>PID: 205  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercodeblockwidth {get { return GetParameter(205); }set { SetParameter(205, value); }}
	/// <summary>PID: 206  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodercodeblockheight_206 {get { return GetParameter(206); }set { SetParameter(206, value); }}
	/// <summary>PID: 206  | Type: read | EXCEPTIONS: Not Available = -1</summary>
	public System.Object Decodercodeblockheight {get { return GetParameter(206); }set { SetParameter(206, value); }}
	/// <summary>PID: 207  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Decodertitle_207 {get { return GetParameter(207); }set { SetParameter(207, value); }}
	/// <summary>PID: 207  | Type: read</summary>
	public System.Object Decodertitle {get { return GetParameter(207); }set { SetParameter(207, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
